import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";

// const garamond = localFont({
//   src: "./fonts/EBGaramond.ttf",
//   variable: "--font-garamond",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
